export { compile, CompilationError, type CompilationResult, type CompileOptions, type CodegenTarget, type PhaseTimings } from "./compiler.js";
export { execute, type TrainingResult, type ExecutionCallbacks } from "./runtime.js";
export { Lexer } from "./lexer.js";
export { Parser } from "./parser.js";
export { Analyzer } from "./analyzer.js";
export { emitTensorFlow, emitPyTorch, emitKeras, emitJAX, emitSummary } from "./codegen.js";
export { resolveDataset, loadIris, loadHousing, loadTitanic, loadWine, loadDigits, parseCSV, registerInlineDataset, unregisterInlineDataset, datasetFromObjects } from "./datasets.js";
export { DiagnosticCollector, formatDiagnostic, formatDiagnostics, Severity, E } from "./diagnostics.js";
export { inferSchema, formatSchema } from "./schema.js";
export { computeFeatureImportance, formatFeatureImportance } from "./explain.js";
export { getCandidates, buildCandidateIR, formatSearchResults } from "./autoarch.js";
export { getTuneConfig, buildTrialIR, totalTrials, formatTuneResults } from "./tune.js";
export { startRepl } from "./repl.js";
export { parseNatural, isNaturalSyntax } from "./natural.js";
export { describeDataset, formatDataPreview, formatDescription, formatCorrelation, formatSample } from "./inspect.js";
export { neurolang } from "./api.js";
export { nl } from "./template.js";
export { startServer } from "./serve.js";
export { neurolangMiddleware } from "./middleware.js";

export type { Token, TokenType } from "./tokens.js";
export type { ProgramNode, StatementNode, ValueNode, SourceLocation, StringValue } from "./ast.js";
export type { NeuralNetworkIR, LayerSpec, DenseLayerSpec, DropoutLayerSpec, BatchNormLayerSpec, TaskType, LossFunction, OptimizerSpec, EarlyStopSpec, LRScheduleSpec } from "./ir.js";
export type { Diagnostic, SourceSpan } from "./diagnostics.js";
export type { InferredSchema } from "./schema.js";
export type { FeatureImportance } from "./explain.js";
export type { ArchCandidate, AutoSearchResult } from "./autoarch.js";
export type { TuneConfig, TuneTrialResult, TuneResult } from "./tune.js";
export type { NaturalParseResult } from "./natural.js";
export type { DataDescription, ColumnStats } from "./inspect.js";
export type { NeurolangResult, InspectResult } from "./api.js";
export type { MiddlewareOptions } from "./middleware.js";
